export const SET_VALUES = 'SET_VALUES';
export const SHOW_MORNING_ROUTINE = 'SHOW_MORNING_ROUTINE';
export const HIDE_MORNING_ROUTINE = 'HIDE_MORNING_ROUTINE';
export const SHOW_EVENING_ROUTINE = 'SHOW_EVENING_ROUTINE';
export const HIDE_EVENING_ROUTINE = 'HIDE_EVENING_ROUTINE';
